
channels:
  - conda-forge

dependencies:
  - python
  - pip
  - jupyterlab
  - ecflow
  - jinja2
  - requests
  - pytest
  - pygraphviz
  - pip:
    - -r requirements.txt

variables:
  QT_MAC_WANTS_LAYER: 1
