# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: pyflow

on:
  push:
    branches: [ "master", "develop" ]
  pull_request:
    branches: [ "master", "develop" ]

jobs:

  # Calls a reusable CI workflow to qa, test & deploy the current repository.
  #   We skip jobs that will result in duplicate jobs, since the code does not depend on the compiler.
  #   It will produce a code coverage report on success and upload it to the codecov service.
  #   If all checks were successful and a new release tag created, the package will be published on PyPI.
  ci:
    name: ci
    uses: ecmwf-actions/reusable-workflows/.github/workflows/ci-python.yml@v1
    with:
      codecov_upload: true
      skip_matrix_jobs: |
        clang-12@ubuntu-20.04
        clang-9@ubuntu-18.04
        clang-12@macos-10.15
      build_package_inputs: |
        self_build: false
        dependencies: |
          ecmwf/ecbuild
          boostorg/boost@refs/tags/boost-1.81.0
          ecmwf/ecflow
        dependency_branch: develop
        dependency_cmake_options: |
          boostorg/boost: "-DBUILD_SHARED_LIBS=ON"
          ecmwf/ecflow: "-DENABLE_UI=OFF"

    secrets:
      pypi_username: ${{ secrets.PYPI_USERNAME }}
      pypi_password: ${{ secrets.PYPI_PASSWORD }}
